### PR TITLE
bump sentry version

### PR DESCRIPTION
**Pull request by bolyachevets**
*Issue #: [15861](https://github.com/bcgov/entity/issues/15861)
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by kialj876** [comment]
@bolyachevets can you update the version conflict pls?

**Comment by bolyachevets** [comment]
> @bolyachevets can you update the version conflict pls?
@kialj876 could I get access to https://console.cloud.google.com/cloud-build/triggers/edit/a730b8c5-2bc6-423d-ab33-8d7d0e69b0ba?project=952634948388 Getting "You do not have sufficient permissions to view this page". Thank you.

**Review by kialj876 — APPROVED** [review]

**Pull request merged**
