### PR TITLE
add release notes link to the footer

### PR DESCRIPTION
**Pull request by patrickpeinanw**
*Issue #:* /bcgov/entity#21079

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://registry-search-dev--pr-260-qt5cfcyh.web.app

**Review by kialj876 — APPROVED** [review]

**Comment by seeker25** [comment]
Awesome

**Pull request merged**
