### PR TITLE
UI - allow doc request open via redirect

### PR DESCRIPTION
**Pull request by kialj876**
*Issue #:* /bcgov/entity#21340

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://registry-search-dev--pr-276-hwryhrzp.web.app

**Review by hfekete — APPROVED** [review]
Looks good

**Pull request merged**
